### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'encode_item'

### ISSUE THREAD

**Issue by Tomona11** [AaronHeee/RecFormer#2]
### Overview

When I followed the steps described in the Training section on the README, I stumbled upon an issue and couldn't move forward.

### Note
I downloaded the processed data and then ran `python save_longformer_ckpt.py` after storing them in the pretrain_data folder. 
The next code `bash lightning_run.sh` gives me the following error. 

Given I go with the default setting including the training strategy `deepspeed_stage_2`, it looks like not running `python zero_to_fp32.py . pytorch_model.bin` could be the culprit but I don't see it created automatically to the checkpoint folder)
Thanks for your guidance.

### Error Detail
`zero_to_fp32.py`

```
Traceback (most recent call last):
  File "./anaconda3/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "./RecFormer-main/lightning_pretrain.py", line 46, in _par_tokenize_doc
    input_ids, token_type_ids = tokenizer_glb.encode_item(item_attr)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'encode_item'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./RecFormer-main/lightning_pretrain.py", line 156, in <module>
    main()
  File "./RecFormer-main/lightning_pretrain.py", line 102, in main
    doc_tuples = list(tqdm(pool_func, total=len(item_attrs), ncols=100, desc=f'[Tokenize] {path_corpus}'))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./anaconda3/lib/python3.11/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "./anaconda3/lib/python3.11/multiprocessing/pool.py", line 873, in next
    raise value
AttributeError: 'NoneType' object has no attribute 'encode_item'
```

**Comment by JiachengLi1995** [comment]
`python zero_to_fp32.py . pytorch_model.bin` should run after the model is pre-trained, and we already had pre-trained checkpoints.
The Error shown in the above because your `tokenizer_glb` is None.
This is unexpected, because we created the `tokenizer` in the line 66 of `lightning_pretrain.py` and `tokenizer_glb = tokenizer` in the line 69.

**Comment by Tomona11** [comment]
Thanks for the comment. I clearly overlooked some of the prerequisite and works fine now. Thank you

**Comment by 1608303198** [comment]
Hello, I encountered the same problem as you, and I would like to ask how you solved it. I hope to get your help.
