### ISSUE TITLE
Difference between RecformerModel and RecformerForSeqRec

### ISSUE THREAD

**Issue by igor17400** [AaronHeee/RecFormer#5]
Firstly, congratulations on the publication! The idea presented is interesting, and the it is very well written.

I'm a bit confused about the distinction between `RecformerModel` and `RecformerForSeqRec`. 

I understand that you used `RecformerForSeqRec` to derive the results in the paper for sequential recommendations. However, I'm curious about the purpose of `RecformerModel`. Is it essentially the model `allenai/longformer-base-4096`, but with variations in token type embedding and item position embedding?

Thanks!

**Comment by JiachengLi1995** [comment]
Yes, RecformerForSeqRec is specifically for the sequential recommendation which has a loss function and item embeddings. RecformerModel is a model for general item representations.

**Comment by igor17400** [comment]
Okay, thanks!
